-- ════════════════════════════════════════════════════════════
-- SpecialSitsIntel — Schéma initial (Phase 0)
-- 6 tables + RLS activée partout + trigger de création de profil.
-- À coller dans l'éditeur SQL Supabase (ou via la CLI).
-- ════════════════════════════════════════════════════════════

-- Hiérarchie des paliers, réutilisée par les policies par palier (Phase 1)
create or replace function public.tier_rank(t text) returns int
  language sql immutable as $$
  select case t when 'free' then 0 when 'analyst' then 1
                when 'institutional' then 2 when 'enterprise' then 3 else 0 end;
$$;

-- 1. profiles (1 ligne par utilisateur auth)
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  nom text,
  fund text,
  aum text,
  tier text not null default 'free'
    check (tier in ('free','analyst','institutional','enterprise')),
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

-- 2. subscriptions (mises à jour UNIQUEMENT par le webhook Stripe serveur)
create table public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  stripe_customer_id text,
  stripe_subscription_id text,
  tier text not null default 'free'
    check (tier in ('free','analyst','institutional','enterprise')),
  status text not null default 'active'
    check (status in ('active','past_due','canceled')),
  current_period_end timestamptz,
  created_at timestamptz not null default now()
);

-- 3. deals (colonnes CLAUDE.md + champs additionnels pour le rendu maquette)
create table public.deals (
  id bigint generated by default as identity primary key,
  nom text not null,
  acquereur text,
  valeur text,
  spread numeric,
  proba_close int,
  ev numeric,
  regulateur text,
  categorie text,
  statut text,
  region text,
  description text,
  ai_commentary text,
  min_tier text not null default 'analyst'
    check (min_tier in ('free','analyst','institutional','enterprise')),
  flag text,             -- f  (drapeau)
  score text,            -- sc (G/A/R/P/B)
  close_estimate text,   -- cl
  price jsonb,           -- pr {u,c,o,sym,cur,ad}
  timeline jsonb,        -- tl [{d,t,x}]
  updated_at timestamptz not null default now()
);

-- 4. deal_updates (audit trail)
create table public.deal_updates (
  id uuid primary key default gen_random_uuid(),
  deal_id bigint references public.deals(id) on delete cascade,
  champ_modifie text,
  ancienne_valeur text,
  nouvelle_valeur text,
  source_url text,
  confiance int check (confiance between 0 and 100),
  auteur text check (auteur in ('ia','humain')),
  created_at timestamptz not null default now()
);

-- 5. sources
create table public.sources (
  id uuid primary key default gen_random_uuid(),
  nom text,
  type text check (type in ('sec','regulateur','news')),
  url text,
  derniere_verif timestamptz
);

-- 6. review_queue
create table public.review_queue (
  id uuid primary key default gen_random_uuid(),
  proposition jsonb,
  source_url text,
  confiance int check (confiance between 0 and 100),
  statut text not null default 'en_attente'
    check (statut in ('en_attente','approuve','rejete')),
  created_at timestamptz not null default now()
);

-- ── RLS activée sur TOUTES les tables ──
alter table public.profiles      enable row level security;
alter table public.subscriptions enable row level security;
alter table public.deals         enable row level security;
alter table public.deal_updates  enable row level security;
alter table public.sources       enable row level security;
alter table public.review_queue  enable row level security;

-- ── Privilèges de rôles (la RLS ci-dessus reste le vrai garde-fou) ──
-- Supabase applique normalement ces grants automatiquement ; on les rend
-- explicites pour garantir que service_role (serveur) et les rôles client
-- aient les privilèges attendus. L'accès aux LIGNES est contrôlé par la RLS.
grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
grant all on all routines in schema public to anon, authenticated, service_role;

-- profiles : chaque user lit/édite SA ligne
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id);
create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

-- subscriptions : chaque user lit SES abonnements (écritures = service_role serveur)
create policy "subscriptions_select_own" on public.subscriptions
  for select using (auth.uid() = user_id);

-- deals, deal_updates, sources, review_queue : AUCUNE policy publique en Phase 0.
-- => inaccessibles au navigateur ; lecture serveur via service_role (qui ignore la RLS).
-- La policy de lecture des deals PAR PALIER sera ajoutée en Phase 1.

-- Trigger : crée une ligne profiles à chaque inscription
create or replace function public.handle_new_user() returns trigger
  language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email);
  return new;
end;
$$;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
